version: '3.8'
services:
  app:
    image: devops/caddy-server:latest
    container_name: caddy-server
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
        - ./config:/app/config

    privileged: true
    pid: host
    ipc: host
    ports:
      - "8080:8080"