server:
    port: 8080
    # Forward headers strategy, make swagger servers url support https
    forward-headers-strategy: framework

spring:
  security:
    user:
      name: admin
      password: admin

caddy:
  api: http://localhost:2019
  reload:
    command: echo "caddy reload"
  file:
    path: ./config/Caddyfile