mode: dev

server:
  port: 18080

spring:
  security:
    user:
      name: admin
      password: admin

caddy:
  api: http://localhost:2019
  reload:
    command: ./config/reload.sh
  file:
    path: ./config/Caddyfile

logging:
  lever:
    root: INFO
    org.springframework.web: INFO